### PR TITLE
Update plugin.yml

### LINKED ISSUE #1: NukkitX
Hello Jason! Sorry for asking, but i can port this plugin to NukkitX? Thanks so much for your answer!

### LINKED ISSUE #2: Could you also create a Mob Spanner plugin?
Could you also create a Mob Spanner plugin?

### PR DESCRIPTION
**Pull request by supercrafter333**

### CODE REVIEW

**Comment by provsalt** [comment]
please follow the template.

**Comment by Wertzui123** [comment]
And you should also test whether it works with the new protocol version.

**Comment by supercrafter333** [comment]
sorry xD
**But it works** :)

**Comment by jasonw4331** [comment]
resolved in 8cae65e62f30bc505ffdf0f269f6a2bab24e403b

**Pull request closed without merging**
